title: Philosophising Monkey
description: >- # this means to ignore newlines until "baseurl:"
  Philosophising Monkey blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  PhilosophisingMonkey

# Build settings
markdown: kramdown
theme: minima
permalink: pretty
future: true
